site_name: Histalign
repo_url: https://github.com/Duguidlab/histalign
repo_name: DuguidLab/histalign

theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.path
    - navigation.top
    - navigation.footer
    - content.code.copy
  icon:
    repo: fontawesome/brands/github
  font:
    text: Montserrat
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: deep-orange
      accent: purple
      toggle:
        icon: material/moon-waxing-crescent
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep-orange
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra_css:
  - css/icons.css

plugins:
  - gen-files:
      scripts:
        - scripts/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            extensions:
              - griffe_pydantic:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - mkdocs-click

copyright: Copyright &copy; 2024-Present Olivier Delrée

nav:
  - Getting started:
      - Installation: index.md
      - Typical workflow: typical-workflow.md
  - Tutorials:
      - Overview: tutorials/index.md
      - Data preparation: tutorials/data-preparation.md
      - Creating your first project: tutorials/your-first-project.md
      - Registration to the CCF: tutorials/registration.md
      - Building a 3D volume: tutorials/volume-building.md
      - Quantifying: tutorials/quantifying.md
      - Visualisation: tutorials/visualisation.md
  - Reference: reference/
